### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by cjessett** [1AICHA/prj-rev-bwfs-dasmoto#4]
(Meets Expectations) Overall, nice work.

Remember to use the `<span>` tag for inline elements that are not links. Also, remember to use relative paths for linking to resources like images.

Again, great use of the `class` attribute to apply styles to multiple elements, nice job.

**Comment by 1AICHA** [comment]
Thanks for your review!
I have certainly learned from my mistakes that you mentioned above.
